# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - PrakharWebApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_9b273fb890cc40f79f81897d51edf493 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2c7e6d4d343d493abde41d3dda89faa1 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_9b273fb890cc40f79f81897d51edf493 }}/ps1607/my-app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'PrakharWebApp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_25d7022b520d4efba7c140f4e61f397a }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_9b273fb890cc40f79f81897d51edf493 }}/ps1607/my-app:${{ github.sha }}'